name: flutter_timer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.0.0
  wave: ^0.0.8
  rxdart: ^0.24.0

flutter:
  uses-material-design: true
